apiVersion: apps/v1
kind: Deployment
metadata:
  name: finale-jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finale-jenkins-app
  template:
    metadata:
      labels:
        app: finale-jenkins-app
    spec:
      containers:
      - name: finale-jenkins-app
        image: soloxbyte/finale-jenkins-app
        ports:
        - containerPort: 3000
